theme: jekyll-theme-cayman
title: "Does tree density influence the number of crimes in San Francisco?"
description: "Finding the connection between trees and crimes using data analysis, visualisations and machine learning"
